[project]
name = "llm-starter-pack"
version = "0.1.0"
description = "My first assignment based on UV, OpenRouter, and LiteLLM."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai-agents>=0.0.19",
    "python-dotenv>=1.1.0",
    "litellm",
]
